# Lisa Loop - Goreleaser configuration

project_name: lisa
dist: dist

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - main: ./cmd/lisa
    binary: lisa
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Commit={{.Commit}}
      - -X main.Date={{.Date}}

archives:
  - id: lisa
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^style:'
      - '^chore:'

release:
  github:
    owner: brainwhocodes
    name: lisa-loop
  mode: replace

nfpms:
  - maintainer: Frank Bria <frank@example.com>
    description: Autonomous AI Development Loop with Charm TUI
    homepage: https://github.com/brainwhocodes/lisa-loop
    license: MIT
    formats:
      - deb
      - rpm

brews:
  - name: lisa
    repository:
      owner: brainwhocodes
      name: homebrew-tap
    description: Autonomous AI Development Loop with Charm TUI
    homepage: https://github.com/brainwhocodes/lisa-loop
    license: MIT

scoops:
  - name: lisa
    description: Autonomous AI Development Loop with Charm TUI
    homepage: https://github.com/brainwhocodes/lisa-loop
    license: MIT
